// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using YogaStudioLRAManagementSystem.Data;

#nullable disable

namespace YogaStudioLRAManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418222840_AddIsActiveToUsers")]
    partial class AddIsActiveToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ATTENDANCE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLOCK_IN");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CLOCK_OUT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("STATUS");

                    b.Property<double?>("TotalHours")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TOTAL_HOURS");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("YS_ATTENDANCES");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Certification")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("CERTIFICATION");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HIRE_DATE");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("LAST_NAME");

                    b.Property<int>("SickLeaveBalance")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SICK_LEAVE_BALANCE");

                    b.Property<int>("StudioRoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STUDIO_ROLE_ID");

                    b.Property<int>("VacationBalance")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("VACATION_BALANCE");

                    b.HasKey("EmployeeId");

                    b.HasIndex("StudioRoleId");

                    b.ToTable("YS_EMPLOYEES");

                    b.HasData(
                        new
                        {
                            EmployeeId = 999,
                            FirstName = "Studio",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Owner",
                            SickLeaveBalance = 0,
                            StudioRoleId = 1,
                            VacationBalance = 0
                        });
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("REQUEST_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("END_DATE");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LEAVE_TYPE_ID");

                    b.Property<string>("Reason")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("REASON");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("START_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("REQUEST_STATUS");

                    b.HasKey("RequestId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("YS_LEAVE_REQUESTS");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("LEAVE_TYPE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<bool>("AffectsBalance")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("AFFECTS_BALANCE");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_PAID");

                    b.Property<int>("MaxDays")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MAX_DAYS");

                    b.Property<int>("MinDays")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MIN_DAYS");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LEAVE_NAME");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("YS_LEAVE_TYPES");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            AffectsBalance = true,
                            IsPaid = true,
                            MaxDays = 14,
                            MinDays = 1,
                            Name = "Vacation"
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            AffectsBalance = true,
                            IsPaid = true,
                            MaxDays = 3,
                            MinDays = 1,
                            Name = "Sick - Paid"
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            AffectsBalance = false,
                            IsPaid = false,
                            MaxDays = 30,
                            MinDays = 1,
                            Name = "Sick - Unpaid"
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            AffectsBalance = false,
                            IsPaid = true,
                            MaxDays = 365,
                            MinDays = 1,
                            Name = "Parental Leave"
                        },
                        new
                        {
                            LeaveTypeId = 5,
                            AffectsBalance = false,
                            IsPaid = true,
                            MaxDays = 5,
                            MinDays = 1,
                            Name = "Bereavement"
                        },
                        new
                        {
                            LeaveTypeId = 6,
                            AffectsBalance = false,
                            IsPaid = false,
                            MaxDays = 7,
                            MinDays = 1,
                            Name = "Certification"
                        });
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.StudioRole", b =>
                {
                    b.Property<int>("StudioRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STUDIO_ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudioRoleId"));

                    b.Property<bool>("RequiresCertification")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("REQUIRES_CERT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("ROLE_NAME");

                    b.HasKey("StudioRoleId");

                    b.ToTable("YS_STUDIO_ROLES");

                    b.HasData(
                        new
                        {
                            StudioRoleId = 1,
                            RequiresCertification = true,
                            RoleName = "Instructor"
                        },
                        new
                        {
                            StudioRoleId = 2,
                            RequiresCertification = false,
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            StudioRoleId = 3,
                            RequiresCertification = false,
                            RoleName = "Cleaner"
                        });
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("MUST_CHANGE_PASSWORD");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("HASH_PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PROFILE_ROLE");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("YS_USERS");

                    b.HasData(
                        new
                        {
                            UserId = 999,
                            EmailAddress = "admin@yogastudio.com",
                            EmployeeId = 999,
                            IsActive = true,
                            MustChangePassword = false,
                            Password = "AQAAAAIAAYagAAAAECnwM22fuVdUcdvOZk2zvO9t7ZQWp9+gnE4Q273VegdJuycMa9iWiphf6TyePThp0w==",
                            Role = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.Attendance", b =>
                {
                    b.HasOne("YogaStudioLRAManagementSystem.Models.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("YogaStudioLRAManagementSystem.Models.StudioRole", "StudioRole")
                        .WithMany("Employees")
                        .HasForeignKey("StudioRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudioRole");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.LeaveRequest", b =>
                {
                    b.HasOne("YogaStudioLRAManagementSystem.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YogaStudioLRAManagementSystem.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.User", b =>
                {
                    b.HasOne("YogaStudioLRAManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("YogaStudioLRAManagementSystem.Models.StudioRole", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
